import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Star from "@/components/minicomponents/Start";
import Providers from "./Providers";
import { getServerSession } from "next-auth";
import { connectDB } from "@/utils/mongoose";
import User from "@/models/Users";
import Info from "@/components/Info";
import TaskContextProvider from "./context/TaskContext";
import ThemeContextProvider from "./context/ThemeContext";
import Background from "@/components/Background";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DevTasks | Lista de Tareas",
  description:
    "Generated by create next app and development by luisfernandomc.com",
};

async function findUser() {
  connectDB();
  const session = await getServerSession();
  if (session) {
    const emailUser = session.user.email;
    const userFound = await User.findOne({ email: emailUser });
    if (!userFound) {
      return true;
    }
    return false;
  }
}

export default async function RootLayout({ children }) {
  const sigOut = await findUser();

  const Stars = [];
  for (let i = 0; i < 200; i++) Stars.push(<Star key={`box-${i}`} />);

  return (
    <html lang="en">
      <Head>
        <meta
          name="viewport"
          content="user-scalable=no, width=device-width, initial-scale=1"
        />
      </Head>
      <body className={`${inter.className} w-full`}>
        <Providers>
          <ThemeContextProvider>
            <TaskContextProvider>
              <header
                className={`h-[30vh] w-[100%] flex justify-center relative overflow-hidden`}
                style={{
                  background: "rgb(68,137,180)",
                  background:
                    "linear-gradient(0deg, rgba(68,137,180,1) 3%, rgba(17,66,99,1) 40%, rgba(7,36,59,1) 74%)",
                }}
              >
                {Stars}
                <Info />
                <Navbar sigOut={sigOut} />
              </header>

              <main
                className={` flex justify-center relative w-[100%] `}
                style={{ height: "70vh" }}
              >
                <Background />
                {children}
              </main>
            </TaskContextProvider>
          </ThemeContextProvider>
        </Providers>
      </body>
    </html>
  );
}
